### PR TITLE
Adding Lab 12 - ensemble methods

### PR DESCRIPTION
**Pull request by ostegm**
@ghego  - lab 12, ensemble methods for your review.

### CODE REVIEW

**Comment by ghego** [comment]
@ostegm 
Could you add an exercise at the end of the second part? maybe a different dataset or a pipeline or doing learning curves or all of these..

**Comment by ostegm** [comment]
@ghego  - added an exercise on predicting phone churn.

**Comment by ghego** [comment]
@ostegm I'm not sure I understand the exercise.
The target variable is a boolean, so I'd expect it to be a classification problem, but then you mention using Regressor methods, so I'm not sure what you're trying to do.

also, should be Random Forest, not Forrest :)

**Comment by ostegm** [comment]
@ghego  - just pushed a new version with some edits to the text. Its not meant to be a regression problem. I started with that but had some issues getting the data I wanted, so I had to switch back to a classification problem. I thought I got all the regression text out but missed some. I think its good now. The exercise is predicting churn for a telecom company.

**Comment by ghego** [comment]
Yes now is good

**Pull request merged**
